apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator-crds
spec:
  interval: 24h
  chart:
    spec:
      chart: eck-operator-crds
      sourceRef:
        kind: HelmRepository
        name: elastic
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  interval: 24h
  targetNamespace: monitoring 
  dependsOn:
    - name: istio-discovery
    - name: elastic-operator-crds
  values:
    managedNamespaces: ["monitoring"]
    createClusterScopedResources: false
    config:
      validateStorageClass: false
    installCRDs: false
    webhook:
      enabled: false
    podAnnotations:
      sidecar.istio.io/inject: "true"
      traffic.sidecar.istio.io/includeInboundPorts: "*"
      traffic.sidecar.istio.io/excludeInboundPorts: "9443"
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic