apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
---