apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
spec:
  install:
    createNamespace: true
  interval: 24h
  chart:
    spec:
      chart: manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio