apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 24h
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./manifests/charts/base
      sourceRef:
        kind: GitRepository
        name: istio