apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-discovery
spec:
  interval: 24h
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
      sourceRef:
        kind: GitRepository
        name: istio