apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: ./manifests/charts/gateways/istio-ingress