apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
spec:
  install:
    createNamespace: true
  interval: 24h
  targetNamespace: kiali-operator
  values:
    cr:
      create: false
      namespace: istio-system
  dependsOn:
    - name: istio-operator
  chart:
    spec:
      chart: kiali-operator
      version: "1.35"
      sourceRef:
        kind: HelmRepository
        name: kiali