apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  targetNamespace: istio-system
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: kiali-server
      version: "1.35"
      sourceRef:
        kind: HelmRepository
        name: kiali