apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  interval: 24h
  targetNamespace: monitoring 
  dependsOn:
    - name: istio-discovery
    - name: prometheus-stack
  values:
    istio_namespace: istio-system
    external_services:
      prometheus: 
        url: "http://prometheus-operated:9090"
      istio:
        istio_identity_domain: cluster.local
      grafana:
        url: "http://monitoring-prometheus-stack-grafana:80"
        auth:
          username: secret:monitoring-prometheus-stack-grafana:admin-user
          password: secret:monitoring-prometheus-stack-grafana:admin-password
  chart:
    spec:
      chart: kiali-server
      version: "1.34"
      sourceRef:
        kind: HelmRepository
        name: kiali